version: 0.2.9.{build}
image: Visual Studio 2017

environment:
  VS_VERSION: vs2017
  QTDIR64: C:\Qt\5.11.1\msvc2017_64
  QTDIR32: C:\Qt\5.11.1\msvc2015
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x86
- x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    
#  - ps: $blockRdp = $true

install:
- ps: (new-object net.webclient).DownloadFile("https://download.microsoft.com/download/4/A/6/4A6AAED8-200C-457C-AB86-37505DE4C90D/msmpisetup.exe", "C:\build_chain\MSMpiSetup.exe")
- C:\build_chain\MSMpiSetup.exe -unattend -minimal
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
- SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\;C:\Program Files (x86)\Inno Setup 5;%PATH%
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

before_build:
- C:\Python36\python c:/build_chain/nelson/tools/update_version/update_version.py
- if %platform%==x64 (set QTDIR=%QTDIR64%) else (set QTDIR=%QTDIR32%)
- if %platform%==x64 (set NELSON_PLATFORM=x64) else (set NELSON_PLATFORM=win32)
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-%NELSON_PLATFORM%.git c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%
- cd "c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%"
- install.bat

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=%NELSON_PLATFORM% /target:"NelSon-gui"  /m:4 

after_build:
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-adv-cli --quiet -f c:\build_chain/nelson/tools/tests_all/runtests_all.nls
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_result/tests_result.nls

artifacts:
  - path: ./*.exe
  - path: ./tests_all*.xml
  - path: ./tests_all*.json


notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
