version: 0.4.11.{build}
image: Visual Studio 2019

environment:
  VS_VERSION: vs2019
  QTDIR64: C:\Qt\5.15.2\msvc2019_64
  QTDIR32: C:\Qt\5.15.2\msvc2019
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x86
- x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))    
#  - ps: $blockRdp = $true

install:
- ps: (new-object net.webclient).DownloadFile("https://download.microsoft.com/download/4/A/6/4A6AAED8-200C-457C-AB86-37505DE4C90D/msmpisetup.exe", "C:\build_chain\MSMpiSetup.exe")
- C:/build_chain/MSMpiSetup.exe -unattend -minimal
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
- SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\;C:\Program Files (x86)\Inno Setup 6;%PATH%
- call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

before_build:
- C:\Python36\python c:/build_chain/nelson/tools/update_version/update_version.py
- if %platform%==x64 (set QTDIR=%QTDIR64%) else (set QTDIR=%QTDIR32%)
- if %platform%==x64 (set NELSON_PLATFORM=x64) else (set NELSON_PLATFORM=win32)
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-%NELSON_PLATFORM%.git c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%
- cd "c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%"
- install.bat

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=%NELSON_PLATFORM% /target:"NelSon-gui" /m:4 

after_build:
- if %platform%==x64 (set GENERATED_EXE=Nelson-%APPVEYOR_BUILD_VERSION%-x86-64.exe) else (set GENERATED_EXE=Nelson-%APPVEYOR_BUILD_VERSION%-x86-32.exe)
- if %platform%==x64 (set GENERATED_ZIP=Nelson-%APPVEYOR_BUILD_VERSION%-x86-64.zip) else (set GENERATED_ZIP=Nelson-%APPVEYOR_BUILD_VERSION%-x86-32.zip)
- if %platform%==x64 (set RESULT_TESTS_XML=tests_all-%APPVEYOR_BUILD_VERSION%-win-x86-64.xml) else (set RESULT_TESTS_XML=tests_all-%APPVEYOR_BUILD_VERSION%-win-x86-32.xml)
- if %platform%==x64 (set RESULT_TESTS_JSON=tests_all-%APPVEYOR_BUILD_VERSION%-win-x86-64.json) else (set RESULT_TESTS_JSON=tests_all-%APPVEYOR_BUILD_VERSION%-win-x86-32.json)
- if %platform%==x64 (set RESULT_BENCHS_XML=benchs_all-%APPVEYOR_BUILD_VERSION%-win-x86-64.xml) else (set RESULT_BENCHS_XML=benchs_all-%APPVEYOR_BUILD_VERSION%-win-x86-32.xml)
- if %platform%==x64 (set RESULT_BENCHS_JSON=benchs_all-%APPVEYOR_BUILD_VERSION%-win-x86-64.json) else (set RESULT_BENCHS_JSON=benchs_all-%APPVEYOR_BUILD_VERSION%-win-x86-32.json)

- "c:/build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --noipc --quiet -f c:/build_chain/nelson/tools/clone_module_skeleton/clone.nls"
- "c:/build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --noipc --quiet -f c:/build_chain/nelson/tools/buildhelp/buildhelp.nls"

- "c:/build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --noipc --quiet -e run('c:/build_chain/nelson/tools/innosetup/innosetup.nls');exit"
- iscc "c:/build_chain/nelson/tools/innosetup/Nelson.iss"

- 'c:/build_chain/nelson/%GENERATED_EXE% /SP- /SILENT /DIR="c:/build_chain/Nelson-%APPVEYOR_BUILD_VERSION%"'
- 7z a -tzip c:/build_chain/%GENERATED_ZIP% c:/build_chain/Nelson-%APPVEYOR_BUILD_VERSION%

# tested in an long path name with space on windows
- mv "c:\build_chain\Nelson-%APPVEYOR_BUILD_VERSION%" "c:\build_chain\Nelson %APPVEYOR_BUILD_VERSION%"
- '"c:/build_chain/Nelson %APPVEYOR_BUILD_VERSION%/bin/%NELSON_PLATFORM%/nelson-cli" --noipc --quiet -f "c:/build_chain/Nelson %APPVEYOR_BUILD_VERSION%/tools/benchs_all/runbenchs_all.nls"'
- '"c:/build_chain/Nelson %APPVEYOR_BUILD_VERSION%/bin/%NELSON_PLATFORM%/nelson-cli" --noipc --quiet -f "c:/build_chain/Nelson %APPVEYOR_BUILD_VERSION%/tools/tests_all/runtests_all.nls"'
- copy "c:\build_chain\%GENERATED_ZIP%" "c:\build_chain\nelson\%GENERATED_ZIP%"
- copy "c:\build_chain\Nelson %APPVEYOR_BUILD_VERSION%\%RESULT_TESTS_XML%" "c:\build_chain\nelson\%RESULT_TESTS_XML%"
- copy "c:\build_chain\Nelson %APPVEYOR_BUILD_VERSION%\%RESULT_TESTS_JSON%" "c:\build_chain\nelson\%RESULT_TESTS_JSON%"
- copy "c:\build_chain\Nelson %APPVEYOR_BUILD_VERSION%\%RESULT_BENCHS_XML%" "c:\build_chain\nelson\%RESULT_BENCHS_XML%"
- copy "c:\build_chain\Nelson %APPVEYOR_BUILD_VERSION%\%RESULT_BENCHS_JSON%" "c:\build_chain\nelson\%RESULT_BENCHS_JSON%"

artifacts:
  - path: ./%GENERATED_EXE%
  - path: ./%GENERATED_ZIP%
  - path: ./%RESULT_TESTS_XML%
  - path: ./%RESULT_TESTS_JSON%
  - path: ./%RESULT_BENCHS_XML%
  - path: ./%RESULT_BENCHS_JSON%

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\nelson
