name: Doxygen

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-?*"

jobs:
  doxygen:
    name: doxygen
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: install dependencies
        run: |
          #sudo apt update;
          #sudo apt upgrade;
          sudo apt -y install doxygen;
          sudo apt -y install graphviz;

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get package version
        uses: myrotvorets/info-from-package-json-action@2.0.0
        id: json_version

      - name: Build doxygen documentation
        run: |
          cd tools/doxygen
          PROJECT_NUMBER=$(git rev-parse --short HEAD) doxygen Doxyfile

      - name: Archive files
        run: |
          cd tools/doxygen
          zip -r nelson_doxygen  nelson_doxygen/

      - name: Save artefacts
        uses: actions/upload-artifact@v3
        with:
          name: nelson-github-action-doxygen-${{ steps.json_version.outputs.packageVersion}}.${{ github.sha }}
          path: tools/doxygen/nelson_doxygen.zip
